import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import type { SeasonPhase } from "@/types";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "football4",
  description: "가상 축구 리그 시뮬레이션 · 개발 진행 중",
};

/**
 * `/[lang]` 루트 레이아웃 — Task 005(10일차 신설), **10일차 2차 검증(팀장 지적)으로
 * 같은 날 구조 변경**.
 *
 * ## 왜 이 파일이 `<html>`/`<body>`를 갖는가 (기존 `src/app/layout.tsx`를 흡수)
 * Next.js 공식 i18n 가이드(`node_modules/next/dist/docs/01-app/02-guides/
 * internationalization.md` "Static Rendering" 절)가 제시하는 정석 구조를 그대로 따른다.
 * 로케일 세그먼트 레이아웃이 `params.lang`을 읽어 `<html lang={lang}>`을 동적으로 설정하려면
 * 그 레이아웃 자신이 **루트 레이아웃**이어야 한다 — 레이아웃은 자기 세그먼트보다 **아래**의
 * 동적 파라미터에 접근할 수 없다(`layout.md` "params" 절: "the root segment down to that
 * layout", 즉 위→아래 방향으로만 흐른다).
 *
 * 오늘 오전 처음 이 세그먼트를 도입했을 때는 진짜 최상단 `src/app/layout.tsx`(`[lang]`보다
 * 위)가 `<html lang="en">`을 하드코딩한 채 `<body>{children}</body>`만 하고 이 파일은
 * children 패스스루만 했다. 이 구조에서는 최상단 레이아웃이 `[lang]` 세그먼트 값을 **절대
 * 읽을 수 없어** 문서 언어가 항상 `en`으로 고정되는 결함이 있었다(D-18 기본 로케일은 ko라
 * `/ko/*` 접근 시에도 `lang="en"`이 선언되는 a11y/SEO 결함 — 10일차 2차 검증에서 발견).
 *
 * ## 조치
 * 종전 `src/app/layout.tsx`의 내용(폰트·`globals.css`·기본 `metadata`)을 전부 이 파일로
 * 옮기고 원본 파일은 삭제했다. `app/` 최상단엔 이제 `[lang]` 외 다른 세그먼트가 없으므로
 * "루트 레이아웃을 생략하면 하위 디렉터리 레이아웃이 그 자리의 루트 레이아웃이 된다"
 * (`layout.md` "Root Layout" 절 — route groups 예시와 동일 원리)는 문서 규칙에 따라 이
 * 파일이 곧 루트 레이아웃이 된다. 헤더/사이드내비/푸터(FR-UI-020)는 여전히 12일차 몫이라
 * 이번엔 추가하지 않는다 — `<body>`는 children 렌더 외 다른 마크업을 아직 갖지 않는다.
 *
 * `lang` 값 자체은 "감지"가 아니라 이미 방문된 URL 세그먼트(`/ko/...`, `/en/...`)를 그대로
 * 읽는 것이므로, `proxy.ts`(로케일 감지·리다이렉트, Task 011 소관) 없이도 정확하다 —
 * 9일차 §7.4 결정("`proxy.ts`는 만들지 않는다")과 충돌하지 않는다.
 *
 * ## `metadata` 변경
 * create-next-app 기본값(`"Create Next App"` / `"Generated by create next app"`)은 이
 * 프로젝트와 무관해 최소한으로만 교체했다 — 실제 사용자向 UI 카피를 새로 만들지 않고
 * 개발 상태를 나타내는 최소한의 기술 설명만 남겨 D-18(번역 카탈로그 경유 원칙) 범위를
 * 넓히지 않는다. 로케일별 메타데이터 지역화(`<title>`/`description`을 `lang`에 따라
 * 분기하는 것)는 Task 011(i18n) 소관으로 이월한다.
 *
 * 참조: `node_modules/next/dist/docs/01-app/02-guides/internationalization.md`,
 * `node_modules/next/dist/docs/01-app/03-api-reference/03-file-conventions/layout.md`
 */
export async function generateStaticParams() {
  return [{ lang: "ko" }, { lang: "en" }];
}

/**
 * 12일차(2026-08-05) Task 005 산출물 — 전역 레이아웃 골격(FR-UI-020).
 *
 * `docs/team-schedule/04-UI기반i18n팀.md` 12일차 표는 산출물을 `src/app/layout.tsx`로
 * 표기하지만, 10일차 결정(위 JSDoc)에 따라 최상단 `layout.tsx`는 만들지 않으므로 헤더/
 * 사이드 내비/푸터를 이 루트 레이아웃(`[lang]/layout.tsx`)의 `<body>`에 둔다.
 *
 * `src/components/**`는 아직 없다(4팀 23일차 이후 생성 — `docs/team-schedule/
 * 04-UI기반i18n팀.md` 소유 경로 절). 그래서 `SiteHeader`/`SideNav`/`SiteFooter`는 별도
 * 파일로 분리하지 않고 이 파일의 로컬 함수로 둔다 — 013A(28~33일차)에서 실제 도메인
 * 컴포넌트가 생기면 이 자리들을 교체한다.
 *
 * 헤더의 4개 자리(리그 스위처·시즌/페이즈 인디케이터·다음 킥오프 타이머·로케일 스위처)는
 * 아직 데이터소스도 i18n도 없어 전부 비활성 placeholder다. 실제 구현 시점: 리그 스위처·
 * 킥오프 타이머는 013A/019~020 화면 연결(28일차 이후), 로케일 스위처는 011의 22일차
 * (`LocaleSwitcher.tsx`), 여기 하드코딩된 한국어 라벨도 그때 번역 키로 교체된다.
 */
export default async function RootLayout(props: LayoutProps<"/[lang]">) {
  const { lang } = await props.params;

  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex min-h-full flex-col">
          <SiteHeader lang={lang} />
          <div className="flex flex-1">
            <SideNav lang={lang} />
            <main className="flex-1">{props.children}</main>
          </div>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}

// mock — 시즌/페이즈 인디케이터 자리. 실제 값은 DataSource 연결(28일차 이후) 시 교체.
const mockSeasonPhase: SeasonPhase = "REGULAR";

function SiteHeader({ lang }: { lang: string }) {
  return (
    <header className="flex items-center justify-between gap-4 border-b border-foreground/10 px-4 py-3">
      {/* 서비스명 — 011에서 번역 키로 교체 예정 */}
      <span className="font-semibold">football4</span>
      <div className="flex items-center gap-2 text-sm">
        <button
          type="button"
          disabled
          className="rounded border border-foreground/20 px-2 py-1 text-foreground/60"
        >
          리그 선택 (준비 중)
        </button>
        <span className="rounded border border-foreground/20 px-2 py-1 text-foreground/60">
          시즌 페이즈: {mockSeasonPhase} (준비 중)
        </span>
        <span className="rounded border border-foreground/20 px-2 py-1 text-foreground/60">
          다음 킥오프까지 -- (준비 중)
        </span>
        <button
          type="button"
          disabled
          className="rounded border border-foreground/20 px-2 py-1 text-foreground/60"
        >
          {lang.toUpperCase()} (준비 중)
        </button>
      </div>
    </header>
  );
}

// 11일차까지 생성된 실제 라우트만 연결한다. admin/bet/my는 2차 대비 예약(플래그 비활성)이라 제외.
const NAV_ITEMS: { label: string; path: string }[] = [
  { label: "리그", path: "leagues" },
  { label: "경기", path: "matches" },
  { label: "선수", path: "players" },
  { label: "팀", path: "teams" },
  { label: "통계", path: "stats" },
  { label: "플레이오프", path: "playoffs" },
  { label: "컵", path: "cup" },
  { label: "이적", path: "transfers" },
  { label: "수상", path: "awards" },
  { label: "아카이브", path: "archive" },
  { label: "스폰서", path: "sponsors" },
];

function SideNav({ lang }: { lang: string }) {
  return (
    <nav className="w-48 shrink-0 border-r border-foreground/10 p-4">
      <ul className="flex flex-col gap-1 text-sm">
        <li>
          <Link href={`/${lang}`}>홈</Link>
        </li>
        {NAV_ITEMS.map((item) => (
          <li key={item.path}>
            <Link href={`/${lang}/${item.path}`}>{item.label}</Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}

function SiteFooter() {
  return (
    <footer className="border-t border-foreground/10 px-4 py-3 text-sm text-foreground/60">
      {/* 개발 진행 상태 표기 — 011에서 번역 키로 교체 예정 */}
      football4 · 개발 진행 중
    </footer>
  );
}
